#eureka:
#  client:
#    serviceUrl:
#      # 生产环境
#      defaultZone: http://118.178.118.151:8801/eureka/


server:
  port: 18801
spring:
  application:
    name: label_manage #全部小写

#访问超时时间 6s
#  ribbon:
#    ReadTimeout: 6000
#    ConnectTimeout: 3000
#  hystrix:
#    command:
#      default:
#        execution:
#          isolation:
#            thread:
#              timeoutInMilliseconds: 6000


#####################################################################################################
# mysql 属性配置
  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://59.202.60.185:3306/tag_system?useUnicode=true&characterEncoding=UTF-8&noAccessToProcedureBodies=true&useSSL=false&serverTimezone=GMT
        username: grxysd
        password: grxysd123456
       # type: com.alibaba.druid.pool.DruidDataSource

#  jpa:
#    hibernate:
#      #ddl-auto: create #ddl-auto:设为create表示每次都重新建表
#      ddl-auto: update #ddl-auto:设为update表示每次都不会重新建表
#    show-sql: true
#####################################################################################################

# mybatis mapper xml 配置
mybatis:
  # mybatis.type-aliases-package：指定domain类的基包，即指定其在*Mapper.xml文件中可以使用简名来代替全类名（看后边的UserMapper.xml介绍）
  type-aliases-package:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml





#####################################################################################################
# 打印日志
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.springms: DEBUG
#####################################################################################################



feign:
  hystrix:
    enabled: true


#user-secret:
#  ribbon:
#    listOfServers: http://101.37.91.207:8811
