eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18801/eureka/


server:
  port: 18805
spring:
  application:
    name: task_manage  #全部小写

  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc


  #访问超时时间 6s
  #  ribbon:
  #    ReadTimeout: 6000
  #    ConnectTimeout: 3000
  #  hystrix:
  #    command:
  #      default:
  #        execution:
  #          isolation:
  #            thread:
  #              timeoutInMilliseconds: 6000


  #####################################################################################################
  # mysql 属性配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.123.80:3306/quartz?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: Zysj@123
    # type: com.alibaba.druid.pool.DruidDataSource

#  jpa:
#    hibernate:
#      #ddl-auto: create #ddl-auto:设为create表示每次都重新建表
#      ddl-auto: update #ddl-auto:设为update表示每次都不会重新建表
#    show-sql: true
#####################################################################################################

# mybatis mapper xml 配置
mybatis:
  # mybatis.type-aliases-package：指定domain类的基包，即指定其在*Mapper.xml文件中可以使用简名来代替全类名（看后边的UserMapper.xml介绍）
  type-aliases-package:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml





#####################################################################################################
# 打印日志
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.springms: DEBUG
#####################################################################################################



feign:
  hystrix:
    enabled: true


#user-secret:
#  ribbon:
#    listOfServers: http://101.37.91.207:8811

